version: '3.4'

services:
  app:
    image: auction-backend
    container_name: auction-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    env_file:
      - .env

  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS

  migrate:
    image: auction-migrate
    container_name: auction-migrate
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    volumes:
      - ./.bin/:/root/
      - ./internal:/schema
    ports:
      - "8000:8000"
    env_file:
      - .env